### ISSUE TITLE
If a Police Officer reaches 5 wanted stars, remove their job/equipment

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/BrokeProtocol#92]

**Comment by DarkRosanne** [comment]
Maybe instead of a 5 stars idea *since if your just defending yourself that can be reached very fast*, make it that if you have a crime bounty count which is of a certain height like 8k+ or something. It shows that you basically have been doing more than just defending yourself, you've been either killing randomly or you are plainly a criminal.

**Comment by UserR00T** [comment]
Job ranks have been added a while back. basically, when your experience gets low enough you'll loose your job. Your experience gets lowered by you guessed it, doing illegal things. [Read more about it here.](https://brokeprotocol.com/floods-fires-frying-pans-job-ranks/`) Thank you for this suggestion!
